#include "gui/GUIButton.hpp"
#include "gui/GUIGalaxy.hpp"
#include "gui/GUIImage.hpp"
#include "gui/GUIInputField.hpp"
#include "gui/GUILabel.hpp"
#include "gui/GUIObject.hpp"
#include "gui/GUIPanel.hpp"
#include "gui/GUISlider.hpp"
